version: "2"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    # networks:
    #   - form_hub_network
  access-services:
    build:
      context: .
      dockerfile: ./apps/access-services/Dockerfile
    depends_on:
      - postgres
    ports:
      - 8000:8000
      - 9229:9229 # debugger port
    volumes:
      - ./apps/access-services:/app/apps/access-services
      - /app/apps/access-services/node_modules
    command: npm start:docker
    environment:
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
      PORT: 8000
    # networks:
    #   - form_hub_network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
# networks:
#   form_hub_network:
#     external: true